### ISSUE TITLE
Bring file fetching logic into app

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord-box3/content-validation-app#9]
The package shouldn't have to handle this.

**Comment by mandolyte** [comment]
@PhotoNomad0 Here is my quick and dirty requirements and design spec.

Assumptions:

- All needed repos can be fetched as zip files and stored in indexedDB
- Performance of using the stored zip files is significantly faster than fetching
  - If not we could try other zip reader packages; 
  - We only need to read, not write
- Fetching can be conditional based the commit hash of fetched repos

Steps:

- Step one. copy the CV package core book package code into CV app and get it working again
  - [x] all files fetched by CV app
  - [x] file content given to CV pkg to validate
  - [x] results are returned as done currently and then displayed for user
- Step two. *unconditionally* fetch all needed repos based selected org and language
  - [x] Will need to swap first two Stepper steps: do org/lang picker first, then show books picker
  - [ ] Once org/lang selected then run the preload function to fetch the repos needed
  - [ ] From the repo zip, use the manifest to obtain bible resources (based book id)
- Step three. *conditionally* fetch all needed repos
  - [ ] Will need to store the commit hash of fetched repos in order to do conditionally fetch
  - [ ] Based on org/lang selection, first check commit hash of each repo
  - [ ] If that repo is already downloaded, do not fetch again
  - [ ] If that repo is not downloaded, then:
    - delete existing out-of-date data plus the stored associated commit hash
    - fetch the repo zip
    - store in indexedDB
    - store the commit hash

**Comment by mandolyte** [comment]
Today (2020-09-24), I will work on step 1 above, namely: move the book package code from the package into the app and get everything working again.

@PhotoNomad0
